[package]
name = "blog_os"
version = "0.1.0"
authors = ["Tomoyuki Nakabayashi <tomo.wait.for.it.yuki@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "0.2.3"
rlibc = "0.1.4"
spin = "0.4.5"
multiboot2 = "0.1.0"
