[package]
name = "blog_os"
version = "0.1.0"
authors = ["Tomoyuki Nakabayashi <tomo.wait.for.it.yuki@gmail.com>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
volatile = "0.2.3"
rlibc = "1.0"
spin = "0.4.5"
multiboot2 = "0.1.0"
bitflags = "1.0"
x86_64 = "0.1.2"
once = "0.3.3"